DELETE FROM gossip_lines;

-- 👨 Gossip about a male user (gender = 'M') — 50 lines
INSERT INTO gossip_lines (gender, content) VALUES
('M', 'Ooh! {user} was caught practicing “I love you” in the mirror… and cried. 😢'),
('M', 'Eeh! Astaghfirollah! {user} ate the whole pizza and said “I’m on a diet!” 🍕'),
('M', 'Lemme tell you a secret… {user} set 5 alarms just to reply “good morning” first. 📱'),
('M', 'Do you know who I saw? {user} blushing at a voice note from @someone! 💬😳'),
('M', 'Oops! {user} sent “I miss you” to the group instead of DM. Chaos! 😱'),
('M', 'Wait till you hear this… {user} named his phone “{user}_in_love”. Cringe! 💔'),
('M', 'Eeh! {user} wore cologne to a Zoom call. Who was he trying to impress? 💼'),
('M', 'Ooh! {user} searched “how to look cool in photos” 10 times. Sad! 📸'),
('M', 'Lemme tell you… {user} has a playlist called “Songs for Her (but she doesn’t know)”. 🎵'),
('M', 'Do you know what I found? {user} saved a wedding ring photo. For who? 👀'),
('M', 'Oops! {user} called his crush “mom” during a call. Trauma. 🛑'),
('M', 'Wait… {user} told his mom he’s “not in love” while blushing. We know. 😏'),
('M', 'Eeh! {user} bought roses and said “for a friend.” Sure, Jan. 🌹'),
('M', 'Ooh! {user} watched love movies all night. Someone’s in their feelings! 🎥'),
('M', 'Lemme tell you a secret… {user} rehearsed a proposal to a pillow. It said no. 😅'),
('M', 'Do you know who I saw? {user} crying at a sad meme. Emotional! 😭'),
('M', 'Oops! {user} liked his crush’s photo from 2018. Time traveler? ⏳'),
('M', 'Wait till you hear this… {user} named his pet “{user}_Jr”. Weak. 🐶'),
('M', 'Eeh! {user} practiced a pickup line in the bathroom. No one was there. 🚽'),
('M', 'Ooh! {user} set his wallpaper to “Hope she texts today.” Relatable. 📱💔'),
('M', 'Lemme tell you… {user} wrote a love letter and deleted it. Tragic. ✍️'),
('M', 'Do you know what he did? {user} searched “how to impress without talking.” 🤫'),
('M', 'Oops! {user} sent a heart emoji to his dad. Family therapy needed. ❤️'),
('M', 'Wait… {user} checked his crush’s profile 12 times today. Obsessed. 🔍'),
('M', 'Eeh! {user} bought two tickets to a concert “for friends.” Sure. 🎟️'),
('M', 'Ooh! {user} listened to “Perfect” by Ed Sheeran on repeat. Cringe level: MAX. 🎶'),
('M', 'Lemme tell you a secret… {user} has a folder named “Future Memories with {user}”. 📁'),
('M', 'Do you know who I saw? {user} whispering “I love you” to his phone. 📞'),
('M', 'Oops! {user} called his crush “boss” in a voice note. Professional love? 🧑‍💼'),
('M', 'Wait till you hear this… {user} named his Wi-Fi “{user}_and_their_crush”. Bold! 🔥'),
('M', 'Eeh! {user} took a selfie with a rose and deleted it. Missed opportunity. 🌹'),
('M', 'Ooh! {user} set a reminder: “Confess feelings.” For 3 AM. Why? ⏰'),
('M', 'Lemme tell you… {user} blushed when someone said “hi.” We saw. 😳'),
('M', 'Do you know what he did? {user} saved a meme that says “I like you.” 😏'),
('M', 'Oops! {user} told his friend “I’m not in love” while staring at their photo. 📸'),
('M', 'Wait… {user} bought a ring “for a friend.” We know the truth. 💍'),
('M', 'Eeh! {user} practiced proposing to his dog. It said “woof.” 💔'),
('M', 'Ooh! {user} watched “The Notebook” and cried. Man of culture. 🎬'),
('M', 'Lemme tell you a secret… {user} has a voice note saved called “Draft Love Confession.” 🎙️'),
('M', 'Do you know who I saw? {user} typing “I love you” for 10 minutes. Just send it! 💬'),
('M', 'Oops! {user} sent a kiss emoji to the wrong group. Drama! 💋'),
('M', 'Wait till you hear this… {user} named his playlist “Songs to Win Her Back.” 🎵'),
('M', 'Eeh! {user} searched “how to be romantic” at 3 AM. Desperate. 🔍'),
('M', 'Ooh! {user} bought chocolate “for a friend.” We know it’s for heartbreak. 🍫'),
('M', 'Lemme tell you… {user} stared at the chat for 20 minutes. Waiting? 👀'),
('M', 'Do you know what he did? {user} renamed his file “Future Wedding Speech.” 🤵'),
('M', 'Oops! {user} called his crush “sis” by mistake. Identity crisis. 🤯'),
('M', 'Wait… {user} set his status to “Thinking of someone…” Who? 🤔'),
('M', 'Eeh! {user} listened to love songs while doing laundry. Mood. 🎧'),
('M', 'Ooh! {user} took a photo of his food and said “This is for her.” It’s just rice. 🍚'),
('M', 'Lemme tell you a secret… {user} dreams about {user} every night. We asked the pillow. 😴');


-- 👩 Gossip about a female user (gender = 'F') — 50 lines
INSERT INTO gossip_lines (gender, content) VALUES
('F', 'Eeh! Astaghfirollah!!! {user} bought new lipstick just to text someone. 💄'),
('F', 'Ooh! {user} took 47 selfies and posted none. Perfectionist or scared? 🤳'),
('F', 'Lemme tell you a secret… {user} set a reminder: “Don’t fall for {user}.” Too late. ⏰'),
('F', 'Do you know who I saw? {user} crying at a rom-com like it’s real life. 🎬😭'),
('F', 'Oops! {user} sent a heart emoji to the wrong chat. We saw it. ❤️'),
('F', 'Wait till you hear this… {user} named her notebook “{user}_or_bust”. Bold! 📓'),
('F', 'Eeh! {user} practiced “casual hi” for 20 minutes. Did she send it? No. 😂'),
('F', 'Ooh! {user} bought a cake and wrote “I love you” on it… then ate it alone. 🎂'),
('F', 'Lemme tell you… {user} has a folder called “Unsent Love Letters.” Tragic. ✍️'),
('F', 'Do you know what she did? {user} searched “how to get noticed by your crush” 8 times. 🔍'),
('F', 'Oops! {user} called her crush “dad” by mistake. Family drama incoming. 🚨'),
('F', 'Wait… {user} told her friend “I’m not in love” while staring at their photo. 📱'),
('F', 'Eeh! {user} bought two tickets to a concert “for friends.” Sure. 🎟️'),
('F', 'Ooh! {user} listened to “Love Story” on repeat for 3 hours. Real-life version? 🎶'),
('F', 'Lemme tell you a secret… {user} wrote “Mrs. {user}” in her diary. We read it. 📖'),
('F', 'Do you know who I saw? {user} practicing a smile in the mirror. For who? 😏'),
('F', 'Oops! {user} liked her crush’s photo from 2019. Time traveler confirmed. ⏳'),
('F', 'Wait till you hear this… {user} named her playlist “Songs for {user}.” Subtle. 🎵'),
('F', 'Eeh! {user} set her wallpaper to “Hope he texts today.” We feel you. 📱💔'),
('F', 'Ooh! {user} recorded a voice note saying “I like you”… saved as “Draft 5”. 😅'),
('F', 'Lemme tell you… {user} checked her crush’s profile 9 times today. Obsessed. 🔍'),
('F', 'Do you know what she did? {user} bought roses “for decoration.” Sure. 🌹'),
('F', 'Oops! {user} sent a kiss emoji to her mom. Awkward family dinner. 💋'),
('F', 'Wait… {user} changed her status to “Thinking of someone…” Who? 🤔'),
('F', 'Eeh! {user} took a photo of her food and said “This is for him.” It’s just salad. 🥗'),
('F', 'Ooh! {user} set a reminder: “Don’t fall in love.” Too late. ⏰'),
('F', 'Lemme tell you a secret… {user} has a voice note called “Confession 3.0.” 🎙️'),
('F', 'Do you know who I saw? {user} whispering a name to her plushie. Cute. 🐻'),
('F', 'Oops! {user} called her crush “bro” in a voice note. Identity crisis. 🤯'),
('F', 'Wait till you hear this… {user} named her Wi-Fi “{user}_and_their_soulmate”. 🔥'),
('F', 'Eeh! {user} searched “how to flirt without talking” at 2 AM. Desperate. 🔍'),
('F', 'Ooh! {user} bought chocolate “for a friend.” We know it’s for heartbreak. 🍫'),
('F', 'Lemme tell you… {user} stared at the chat for 25 minutes. Waiting? 👀'),
('F', 'Do you know what she did? {user} renamed her file “Future Wedding Speech.” 💍'),
('F', 'Oops! {user} sent a love song to the group by mistake. Drama! 🎶'),
('F', 'Wait… {user} watched a proposal video and sighed. Dreams! 💭'),
('F', 'Eeh! {user} practiced saying “I love you” in the car. No one heard. 🚗'),
('F', 'Ooh! {user} set her alarm for “Confess feelings.” At midnight. Why? ⏰'),
('F', 'Lemme tell you a secret… {user} dreams about {user} every night. We asked the stars. ✨'),
('F', 'Do you know who I saw? {user} typing “I like you” for 15 minutes. Just send it! 💬'),
('F', 'Oops! {user} liked her crush’s selfie from 3 years ago. Awkward. ⏳'),
('F', 'Wait till you hear this… {user} bought a gift “for a friend.” Mystery! 🎁'),
('F', 'Eeh! {user} listened to love songs while doing homework. Mood. 🎧'),
('F', 'Ooh! {user} took a photo of the moon and said “This is for him.” Poetic. 🌙'),
('F', 'Lemme tell you… {user} has a folder named “Future Memories with {user}”. 📁'),
('F', 'Do you know what she did? {user} set her ringtone to “Marry You.” Hint! 💍'),
('F', 'Oops! {user} called her crush “bestie” while blushing. We see you. 😳'),
('F', 'Wait… {user} changed her bio to “Single but…” and deleted it. Weak. 💔'),
('F', 'Eeh! {user} searched “signs he likes you” 10 times. Case closed. 🔍'),
('F', 'Ooh! {user} bought a heart-shaped pillow. For who? We know. 💘'),
('F', 'Lemme tell you a secret… {user} wrote a poem about {user}. We read it. 📜');



-- 👩 Gossip about a female user (gender = 'F') — 50 lines
INSERT INTO gossip_lines (gender, content) VALUES
('F', 'Eeh! Astaghfirollah!!! {user} bought new lipstick just to text someone. 💄'),
('F', 'Ooh! {user} took 47 selfies and posted none. Perfectionist or scared? 🤳'),
('F', 'Lemme tell you a secret… {user} set a reminder: “Don’t fall for {user}.” Too late. ⏰'),
('F', 'Do you know who I saw? {user} crying at a rom-com like it’s real life. 🎬😭'),
('F', 'Oops! {user} sent a heart emoji to the wrong chat. We saw it. ❤️'),
('F', 'Wait till you hear this… {user} named her notebook “{user}_or_bust”. Bold! 📓'),
('F', 'Eeh! {user} practiced “casual hi” for 20 minutes. Did she send it? No. 😂'),
('F', 'Ooh! {user} bought a cake and wrote “I love you” on it… then ate it alone. 🎂'),
('F', 'Lemme tell you… {user} has a folder called “Unsent Love Letters.” Tragic. ✍️'),
('F', 'Do you know what she did? {user} searched “how to get noticed by your crush” 8 times. 🔍'),
('F', 'Oops! {user} called her crush “dad” by mistake. Family drama incoming. 🚨'),
('F', 'Wait… {user} told her friend “I’m not in love” while staring at their photo. 📱'),
('F', 'Eeh! {user} bought two tickets to a concert “for friends.” Sure. 🎟️'),
('F', 'Ooh! {user} listened to “Love Story” on repeat for 3 hours. Real-life version? 🎶'),
('F', 'Lemme tell you a secret… {user} wrote “Mrs. {user}” in her diary. We read it. 📖'),
('F', 'Do you know who I saw? {user} practicing a smile in the mirror. For who? 😏'),
('F', 'Oops! {user} liked her crush’s photo from 2019. Time traveler confirmed. ⏳'),
('F', 'Wait till you hear this… {user} named her playlist “Songs for {user}.” Subtle. 🎵'),
('F', 'Eeh! {user} set her wallpaper to “Hope he texts today.” We feel you. 📱💔'),
('F', 'Ooh! {user} recorded a voice note saying “I like you”… saved as “Draft 5”. 😅'),
('F', 'Lemme tell you… {user} checked her crush’s profile 9 times today. Obsessed. 🔍'),
('F', 'Do you know what she did? {user} bought roses “for decoration.” Sure. 🌹'),
('F', 'Oops! {user} sent a kiss emoji to her mom. Awkward family dinner. 💋'),
('F', 'Wait… {user} changed her status to “Thinking of someone…” Who? 🤔'),
('F', 'Eeh! {user} took a photo of her food and said “This is for him.” It’s just salad. 🥗'),
('F', 'Ooh! {user} set a reminder: “Don’t fall in love.” Too late. ⏰'),
('F', 'Lemme tell you a secret… {user} has a voice note called “Confession 3.0.” 🎙️'),
('F', 'Do you know who I saw? {user} whispering a name to her plushie. Cute. 🐻'),
('F', 'Oops! {user} called her crush “bro” in a voice note. Identity crisis. 🤯'),
('F', 'Wait till you hear this… {user} named her Wi-Fi “{user}_and_their_soulmate”. 🔥'),
('F', 'Eeh! {user} searched “how to flirt without talking” at 2 AM. Desperate. 🔍'),
('F', 'Ooh! {user} bought chocolate “for a friend.” We know it’s for heartbreak. 🍫'),
('F', 'Lemme tell you… {user} stared at the chat for 25 minutes. Waiting? 👀'),
('F', 'Do you know what she did? {user} renamed her file “Future Wedding Speech.” 💍'),
('F', 'Oops! {user} sent a love song to the group by mistake. Drama! 🎶'),
('F', 'Wait… {user} watched a proposal video and sighed. Dreams! 💭'),
('F', 'Eeh! {user} practiced saying “I love you” in the car. No one heard. 🚗'),
('F', 'Ooh! {user} set her alarm for “Confess feelings.” At midnight. Why? ⏰'),
('F', 'Lemme tell you a secret… {user} dreams about {user} every night. We asked the stars. ✨'),
('F', 'Do you know who I saw? {user} typing “I like you” for 15 minutes. Just send it! 💬'),
('F', 'Oops! {user} liked her crush’s selfie from 3 years ago. Awkward. ⏳'),
('F', 'Wait till you hear this… {user} bought a gift “for a friend.” Mystery! 🎁'),
('F', 'Eeh! {user} listened to love songs while doing homework. Mood. 🎧'),
('F', 'Ooh! {user} took a photo of the moon and said “This is for him.” Poetic. 🌙'),
('F', 'Lemme tell you… {user} has a folder named “Future Memories with {user}”. 📁'),
('F', 'Do you know what she did? {user} set her ringtone to “Marry You.” Hint! 💍'),
('F', 'Oops! {user} called her crush “bestie” while blushing. We see you. 😳'),
('F', 'Wait… {user} changed her bio to “Single but…” and deleted it. Weak. 💔'),
('F', 'Eeh! {user} searched “signs he likes you” 10 times. Case closed. 🔍'),
('F', 'Ooh! {user} bought a heart-shaped pillow. For who? We know. 💘'),
('F', 'Lemme tell you a secret… {user} wrote a poem about {user}. We read it. 📜');



-- 👨 Annoyed gossip (M) – 5 lines
INSERT INTO gossip_lines (gender, content) VALUES
('M', 'Hey hey! Stop asking about {user}! Go talk to him or at least send a meme! 🧐'),
('M', 'I’m tired of telling you about {user}… sounds like you have fish memory! 🐟'),
('M', 'It’s not my business! Go ask someone else… stop stalking {user}’s updates! 🕵️‍♂️'),
('M', 'Why are you so obsessed with {user}? Is he your crush or your life mission? 💘'),
('M', 'Seriously? Again about {user}? I’m starting to think YOU should propose! 💍');

-- 👩 Annoyed gossip (F) – 5 lines
INSERT INTO gossip_lines (gender, content) VALUES
('F', 'Eeh! Astaghfirollah! Stop asking about {user}! Go pray or get a hobby! 🤲'),
('F', 'Lemme tell you… I’ve said the same thing 5 times! Do you write it down or what? 📝'),
('F', 'It’s not my job to follow {user}! Go check her status yourself! 📱'),
('F', 'Why are you so interested in {user}? Is she your crush or your drama series? 🎭'),
('F', 'Ooh! You again? Asking about {user}? Maybe YOU should confess first! 💬');

-- 🤫 Annoyed gossip (NULL) – 5 lines
INSERT INTO gossip_lines (gender, content) VALUES
(NULL, 'Hey hey! Stop asking about {user}! Go do something positive in your life! ✨'),
(NULL, 'I’m tired of repeating myself… sounds like you need a notebook! 📒'),
(NULL, 'It’s not my business… go ask someone else. Stop following {user} like a fan account! 📸'),
(NULL, 'Why are you so interested in {user}? Is this love or just boredom? 😏'),
(NULL, 'Again about {user}? Maybe YOU should start a podcast about them! 🎙️');

