

PRAGMA encoding = "UTF-8";

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    username  TEXT NULL,
    first_name TEXT NULL,
    last_name TEXT NULL,
    language_code TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chats (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);